name: Замер веса (Analyze Bundle)

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

# СИЛОВОЙ НАКАЗ ДЛЯ ТИШИНЫ В ЛЕТОПИСИ
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Взять код
        uses: actions/checkout@v4.2.2

      - name: Устроить Свод Жизни (Node.js 24)
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '24.x'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Вернуть припасы (node_modules)
        uses: actions/cache@v4.2.0 # Обновили до свежего лика
        with:
          path: '**/node_modules'
          key: node_modules-${{ runner.arch }}-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Собрать припасы
        run: yarn install --frozen-lockfile

      - name: Вернуть прошлую сборку
        uses: actions/cache@v4.2.0 # Обновили до свежего лика
        id: restore-build-cache
        env:
          cache-name: cache-next-build
        with:
          path: .next/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Сборка Спутником
        run: ./node_modules/.bin/next build

      - name: Замерить вес лоскутов
        run: npx -p nextjs-bundle-analysis@0.5.0 report

      - name: Сложить итоги замера на склад
        uses: actions/upload-artifact@v4.6.0 # Обновили до самого свежего
        with:
          path: .next/analyze/__bundle_analysis.json
          name: bundle_analysis.json

      - name: Скачать веса из основного корня
        uses: dawidd6/action-download-artifact@v3
        if: success() && github.event.number
        with:
          workflow: analyze.yml
          branch: ${{ github.event.pull_request.base.ref }}
          name: bundle_analysis.json
          path: .next/analyze/base/bundle

      - name: Сравнить веса с прошлыми
        if: success() && github.event.number
        run: ls -laR .next/analyze/base && npx -p nextjs-bundle-analysis compare

      - name: Сложить текст доклада на склад
        uses: actions/upload-artifact@v4.6.0
        with:
          name: analysis_comment.txt
          path: .next/analyze/__bundle_analysis_comment.txt

      - name: Сохранить номер прошения (PR)
        run: echo ${{ github.event.number }} > ./pr_number

      - name: Сложить номер на склад
        uses: actions/upload-artifact@v4.6.0
        with:
          name: pr_number
          path: ./pr_number
