name: Вестник Дискорда (Discord Notify)

on:
  pull_request_target:
    types: [opened, ready_for_review]

permissions: {}

# СИЛОВОЙ НАКАЗ ДЛЯ ТИШИНЫ В ЛЕТОПИСИ
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  check_maintainer:
    # Оставляем как есть, это обращение к общим правилам Фейсбука
    uses: facebook/react/.github/workflows/shared_check_maintainer.yml@main
    permissions:
      contents: read
    with:
      actor: ${{ github.event.pull_request.user.login }}

  notify:
    if: ${{ needs.check_maintainer.outputs.is_core_team == 'true' }}
    needs: check_maintainer
    runs-on: ubuntu-latest
    steps:
      - name: Весть в Дискорд (Webhook)
        # Обновляем до v6.0.0 (или оставляем текущую, если она уже свежая)
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-author-name: ${{ github.event.pull_request.user.login }}
          embed-author-url: ${{ github.event.pull_request.user.html_url }}
          embed-author-icon-url: ${{ github.event.pull_request.user.avatar_url }}
          embed-title: '#${{ github.event.number }} (+${{github.event.pull_request.additions}} -${{github.event.pull_request.deletions}}): ${{ github.event.pull_request.title }}'
          embed-description: ${{ github.event.pull_request.body }}
          embed-url: ${{ github.event.pull_request.html_url }}
