name: Проверка вязи и заголовков (Site Lint)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions: {}

# СИЛОВОЙ НАКАЗ ДЛЯ ТИШИНЫ В ЛЕТОПИСИ
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  lint:
    runs-on: ubuntu-latest

    name: Проверка на Node.js 24.x

    steps:
      - name: Взять код
        uses: actions/checkout@v4.2.2

      - name: Устроить Свод Жизни (Node.js 24)
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 24.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Вернуть припасы (node_modules)
        uses: actions/cache@v4.2.0
        with:
          path: '**/node_modules'
          key: node_modules-${{ runner.arch }}-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Собрать припасы
        run: yarn install --frozen-lockfile

      - name: Проверить чистоту вязи
        run: yarn ci-check
        # Если хочешь, чтобы сайт выходил в мир даже с мелкими огрехами,
        # добавь ниже: continue-on-error: true
